# Generated by Django 4.2 on 2023-04-14 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_alter_movieorder_movie_alter_movieorder_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="users",
            field=models.ManyToManyField(
                related_name="users_movies",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
